---
title: The Sweet Kitchen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    show_meta: false
    comments: false
    author: thesweetkitchen
- scope:
    path: ''
    type: posts
  values:
    show_meta: true
    comments: false
    author: thesweetkitchen
slogan: A little sweetness goes a long way
description: A woman's path to learning how to bake her own creations, one ingredient
  at a time.
credits: <p>Created with &hearts; by <a href="http://phlow.de/">Phlow</a>. Thank you
  for sharing <a href="http://phlow.github.io/feeling-responsive/">Feeling Responsive</a>.</p>
author: Yin
url: thesweet.kitchen
baseurl: ''
improve_content: https://github.com/thesweetkitchen/edit/gh-pages
urlimg: https://thesweetkitchen.github.io/images/
logo: logo.png
gems:
- jekyll-asciidoc
- jekyll-gist
- jekyll-paginate
paginate: 5
paginate_path: blog/page:num
markdown: kramdown
permalink: "/:categories/:title/"
highlight: rouge
excerpt_separator: "<!--more-->"
include:
- ".htaccess"
exclude:
- ".sass-cache"
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- INSTALL.md
language: en
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
  endings: all
  profile: false
  ignore:
    envs:
    - development
google_site_verification: mWAqBuPEzQYwbFTE_SSes_BnsyogQChRw7L1c3mO110
favicon-32x32: favicon-32x32.png
touch-icon-192x192: touch-icon-192x192.png
apple-touch-icon-180x180-precomposed: apple-touch-icon-180x180-precomposed.png
apple-touch-icon-152x152-precomposed: apple-touch-icon-152x152-precomposed.png
apple-touch-icon-144x144-precomposed: apple-touch-icon-144x144-precomposed.png
apple-touch-icon-120x120-precomposed: apple-touch-icon-120x120-precomposed.png
apple-touch-icon-114x114-precomposed: apple-touch-icon-114x114-precomposed.png
apple-touch-icon-76x76-precomposed: apple-touch-icon-76x76-precomposed.png
apple-touch-icon-72x72-precomposed: apple-touch-icon-72x72-precomposed.png
apple-touch-icon-precomposed: apple-touch-icon-precomposed.png
msapplication_tileimage: msapplication_tileimage.png
msapplication_tilecolor: "#fabb00"
og_image: http://images.phlow.de/phlow/phlow_de-logo-512x.png
og_locale: en_EN
og_type: website
socialmedia:
  twitter: thesweetkitchen
  facebook: cookinthesweetkitchen
disqus_shortname: thesweetkitchen
sass:
  sass_dir: _sass
  style: :compressed
google_analytics_tracking_id: UA-98425471-1
asciidoctor-enabled: false
asciidoctor:
  description: testtewtetrue
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font
