---
title: The Sweet Kitchen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: play@thesweet.kitchen
description: Journey on how to bake.
baseurl: 
url: http://thesweet.kitchen
twitter_username: 
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
